"""Regenerate notebook/cell2_write_submission.py from submission/ and validate_submission.py.

Run after editing anything under submission/:   python build_cells.py
The generated cell is self-contained: paste it into Kaggle and it writes the
submission folder, validates it, and packs /kaggle/working/submission.zip.
"""
from pathlib import Path

HERE = Path(__file__).resolve().parent
SUBMISSION = HERE / "submission"
OUT = HERE / "notebook" / "cell2_write_submission.py"

TEMPLATE = '''# CELL 2: write, validate and pack the competition submission.
# GENERATED by kaggle/gemma4_submission/build_cells.py from submission/ - edit those files, not this cell.
from pathlib import Path
import importlib.util
import shutil

WORK = Path("/kaggle/working")
SUBMISSION = WORK / "submission"
ZIP = WORK / "submission.zip"

FILES = {files}

VALIDATOR = {validator}

if SUBMISSION.exists():
    shutil.rmtree(SUBMISSION)
for rel, text in FILES.items():
    path = SUBMISSION / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
(WORK / "validate_submission.py").write_text(VALIDATOR, encoding="utf-8")
spec = importlib.util.spec_from_file_location("validate_submission", WORK / "validate_submission.py")
vs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(vs)
errors = vs.validate(SUBMISSION)
if errors:
    raise RuntimeError("Submission invalid:\\n" + "\\n".join(errors))
vs.pack(SUBMISSION, ZIP)
print(f"Submission OK: {{len(FILES)}} files -> {{ZIP}}")
'''


def render() -> str:
    files = {p.relative_to(SUBMISSION).as_posix(): p.read_text(encoding="utf-8")
             for p in sorted(SUBMISSION.rglob("*")) if p.is_file() and p.name != ".gitkeep"}
    body = "{\n" + "".join(f"    {k!r}: {v!r},\n" for k, v in files.items()) + "}"
    validator = (HERE / "validate_submission.py").read_text(encoding="utf-8")
    return TEMPLATE.format(files=body, validator=repr(validator))


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8")
    print("Wrote", OUT)
